api:
  # REST API HTTP server port
  port: 8080

members:
  # Number of days since last seen after which player is considered inactive
  inactive-days: 30

alts:
  # Maximum number of alts you can have
  max: 10

join:
  # The number of minutes after which requests/invitations to join a nation expire
  request-expire-minutes: 1440

# Ban players upon death
death-ban:
  enabled: true
  message: <lang:deathScreen.title>

  # Ban durations
  progression:
    - PT1M
    - PT2M
    - PT5M
    - PT10M
    - PT20M
    - PT45M
    - PT1H30M
    - PT3H
    - PT6H
    - PT12H
    - P1D
    - P3D
    - P7D
    - P14D

relative-time:
  seconds: <t> <format:'0#seconds|1#second|1<seconds'>
  minutes: <t> <format:'0#minutes|1#minute|1<minutes'>
  hours: <t> <format:'0#hours|1#hour|1<hours'>
  days: <t> <format:'0#days|1#day|1<days'>
  months: <t> <format:'0#months|1#month|1<months'>
  years: <t> <format:'0#years|1#year|1<years'>
  future: in <t>
  past: <t> ago
  duration: for <t>
  duration-indefinite: <u><b>forever</b></u>

staff-team:
  id: staff
  name: <hover:show_text:'The shield that guards the realms of men.'><dark_red><b>STAFF</b></dark_red></hover>
